# Generated by Django 4.2.4 on 2023-08-29 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='file',
            field=models.FileField(null=True, upload_to='submissions/'),
        ),
    ]
